//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalQuestionnaire
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class QuestionnaireForm
    {
        //[Key]
        //[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }
        public int UserId { get; set; }
        public string QuestionnaireAnswer { get; set; }
        public string LanguageType { get; set; }
        public string Date { get; set; }
        public string ReferralImage { get; set; }
        public string MedicationFile { get; set; }
    
        public virtual User User { get; set; }
    }
}
